version: '3.4'

services:

  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=swe1user
      - POSTGRES_PASSWORD=swe1pw
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  database-data:
  pgadmin: